target “TLGaodeMap” do
    pod 'AMapLocation' #定位SDK
    pod 'Masonry'      #自动布局
    pod 'AMap3DMap'    #3D地图SDK
    pod 'AMapNavi'     #导航SDK 已包含3D地图，IFDA版本 无需单独引入3D地图
    pod 'AMapSearch'   #搜索服务SDK
end
